version: "3.7"
services:

  web:
    image: "node:current"
    privileged: true
    tty: true
    stdin_open: true
    restart: always
    working_dir: /home/node/app
    environment:
      - NODE_ENV=devlopment
    volumes:
      - ./src/:/home/node/app
    ports:
      - "3000:3000"
    #command: "npm run dev"
    networks:
      - backend

networks:
  backend: